elasticsearch:
  image: elasticsearch
  container_name: elasticsearch
  ports:
    - 9200:9200
kibana:
  image: kibana
  container_name: kibana
  links:
    - elasticsearch
  ports:
    - 5601:5601
logstash:
  image: logstash
  container_name: logstash
  ports:
    - 5000:5000
  volumes:
    - ./etc:/conf
    - ./logs:/logs
  links:
    - elasticsearch
  command: sh -c "logstash -f /conf/logstash.conf"
 
